version: '2'
services:
    contactmono-app:
        image: contactmono
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://contactmono-mysql:3306/contactmono?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    contactmono-mysql:
        extends:
            file: mysql.yml
            service: contactmono-mysql
